apiVersion: v2
name: sitesearch
appVersion: 3.2.0
annotations:
  io.giantswarm.application.team: honeybadger
description: OpenSearch-based search engine for the Giant Swarm documentation at https://docs.giantswarm.io/
home: https://github.com/giantswarm/sitesearch
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 1.3.8
