name: sitesearch-app
image:
  registry: gsoci.azurecr.io
  name: giantswarm/opensearch
  # used by renovate
  # repo: gsoci.azurecr.io/giantswarm/opensearch
  tag: 3.4.0

# OpenSearch configuration
opensearch:
  clusterName: sitesearch
  nodeName: sitesearch-node-1
  singleNode: true
  # Disable security for single node setup (can be enabled later)
  securityDisabled: true
  # Force clean start - removes incompatible data on startup
  forceCleanStart: false

resources:
  requests:
    cpu: 100m
    memory: 650M
  limits:
    cpu: 500m
    memory: 800M

global:
  podSecurityStandards:
    enforced: false
